---
# <!--td-commons-settings-labels-start-->
labelPRBasedOnFilePath:
  cicd:
    - .github/workflows/**
  project-config:
    - .github/settings.yml
  chore:
    - .github/**
  documentations:
    - docs/**
    - mkdocs.yml
    - .github/ISSUE_TEMPLATE/**
    - .github/pull_request_template.md
# <!--td-commons-settings-labels-end-->
