on:
  push:

jobs:
  static:
    uses: nolte/gh-plumbing/.github/workflows/reusable-pre-commit.yaml@develop
  security:
    uses: nolte/gh-plumbing/.github/workflows/reusable-trivy.yaml@develop
  chain-bench:
    uses: nolte/gh-plumbing/.github/workflows/reusable-chain-bench.yaml@develop
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
