on:
  push:

jobs:
  static:
    uses: nolte/gh-plumbing/.github/workflows/reuseable-pre-commit.yaml@feature/reusing-workflows
  security:
    uses: nolte/gh-plumbing/.github/workflows/reuseable-trivy.yaml@feature/reusing-workflows
