name: Dependency Review

on:
  push:
#on:
#  pull_request:

permissions:
  contents: read

jobs:
  static:
    uses: nolte/gh-plumbing/.github/workflows/reuseable-dependency-review.yaml.yaml@feature/dependency-review
