on:
  release:
    types: [published]

jobs:
  publish_docs:
    uses: nolte/gh-plumbing/.github/workflows/reuseable-mkdocs.yaml@feature/reusing-workflows
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
