on:
  push:
    branches:
      - develop

jobs:
  update_release_draft:
    uses: nolte/gh-plumbing/.github/workflows/reuseable-release-drafter.yml@develop
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
