name: Publishing Ansible Galaxy Role

on:
  workflow_call:
    secrets:
      galaxy_api_key:
        required: true

jobs:
  molecule:
    name: "Push Role"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.2

      - name: galaxy
        uses: robertdebock/galaxy-action@1.2.1
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
