name: Release Drafter

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  update_release_draft:
    name: Update Release Draft
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
