name: Reusable — Ansible Molecule

on:
  workflow_call:
    inputs:
      molecule_working_dir:
        description: 'The Molecule Working Directory'
        type: string
      molecule_args:
        description: 'Molecule Extra Arguments'
        type: string

jobs:
  molecule:
    name: "Ansible Molecule Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Start ansible molecule Based Tests
        uses: gofrolist/molecule-action@2f3cabc46b44fd81be92d7879407fde9c4479df1 # v2.7.79
        with:
          molecule_working_dir: ${{ inputs.molecule_working_dir }}
          molecule_args: ${{ inputs.molecule_args }}
