name: Release Deliver Docs

on:
  workflow_call:
    inputs:
      requirements:
        description: 'path of the requirements dependencies file'
        required: false
        default: "./requirements-dev.txt"
        type: string
    secrets:
      token:
        required: true

jobs:
  publish_docs:
    name: "Publish the HTML Documentation"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3.0.2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.25
        env:
          GITHUB_TOKEN: ${{ secrets.token  }}
          REQUIREMENTS: ${{ inputs.requirements }}
