name: CI Static Tests

on:
  workflow_call:

jobs:
  static:
    name: "Static CI Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3.0.2

      - uses: actions/setup-python@v3

      - uses: pre-commit/action@v3.0.0
