name: CI Static Tests

on:
  workflow_call:

jobs:
  static:
    name: "Static CI Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3.3.0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - uses: pre-commit/action@v3.0.0
