on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    uses: nolte/gh-plumbing/.github/workflows/reuseable-stale.yaml@feature/reusing-workflows
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
