name: Stale

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    uses: nolte/gh-plumbing/.github/workflows/reusable-stale.yaml@fix/388-pin-third-party-actions
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
